### PR TITLE
Fixes crash on exceptions during internal CD github issue #2

### PR DESCRIPTION
**Pull request by santagada**
Encoding is the function that turns strings into bytes

### CODE REVIEW

**Comment by horeah** [comment]
I have already stumbled into this myself, and I came up with a somewhat similar fix on my local master -- but I had not pushed it (collaborating with other developers on PyCmd happens rarely enough for me to become careless, sorry).

The question is: is there a need to encode anything? My local fix simply removes the call to decode() altogether -- am I missing something?

**Comment by santagada** [comment]
You don't need the u prefix in strings anymore on python 3.
Also no need to encode if the stdout is open in text mode
And finally there's FileNotFound exception class now, and with that you can format a better error message for those quite easily.

**Comment by horeah** [comment]
Yup, sounds about right 😄 
Will you submit a new pull request with the "full" fix? Or should I fix it myself?

**Comment by santagada** [comment]
Fixed the issues and added tests

**Review by horeah — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
